server:
  port: 8100
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:oracle:thin:@DESKTOP-P3N2C1R:1521/XE
    username: system
    password: sdbanco
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: true
